a = input('Как Вас зовут? ')
b = int(input('Сколько Вам лет? '))
c = float(input('Введите число с плавающей точкой: '))
print()
print('Ваше имя - ', a, type(a),'\nВозраст - ', b, type(b),'\nЧисло - ', c, type(c))
